### ISSUE TITLE
createinfos.py generates an invalid json

### ISSUE THREAD

**Issue by eric-void** [TVsIan/bezeltools#1]
Json file generated by createinfos.py ends with a ",", but this makes the json invalid, and batocera V38 can't read it and ignores the info (so viewport in not correctly generated in retroarch files).
For example, json generated by createinfos:
```
{
 "width":1920,
 "height":1080,
 "top":61,
 "left":241,
 "bottom":60,
 "right":240,
 "opacity":0.7,
 "messagex":0.22,
 "messagey":0.12,
}
```

Correct json:
```
{
 "width":1920,
 "height":1080,
 "top":61,
 "left":241,
 "bottom":60,
 "right":240,
 "opacity":0.7,
 "messagex":0.22,
 "messagey":0.12
}
```

(Note the missing "," in messagey).

The fix is simple, you must change line 130 from
```
infoFile.write(' "messagey":0.12,\n')
```
to
```
infoFile.write(' "messagey":0.12\n')
```

**Comment by TVsIan** [comment]
Fixed.
